export type AnnualLeaveLocale = "ko" | "en";

export const annualLeaveContent = {
  ko: {
    title: "연차수당 계산기",
    metaTitle: "연차수당 계산기",
    category: "근로·휴가 계산기",
    description:
      "근속·출근 조건과 통상시급으로 예상 연차 일수와 미사용 연차수당을 계산합니다.",
    intro: "근로기준법 제60조의 기본 산식을 적용한 참고용 추정치입니다.",
    input: "근속 및 출근 조건",
    completedYears: "완료한 근속연수",
    years: "년",
    attendance: "직전 1년 출근율이 80% 이상",
    fullMonths: "개근한 달 수",
    months: "개월",
    usedDays: "사용한 연차",
    hourlyWage: "통상시급",
    dailyHours: "1일 소정근로시간",
    won: "원",
    days: "일",
    calculate: "연차 계산하기",
    reset: "초기화",
    error: "입력값을 확인해 주세요.",
    result: "예상 연차수당",
    allowance: "미사용 연차수당",
    dailyWage: "1일 통상임금",
    granted: "발생 일수",
    seniority: "근속 가산",
    remaining: "남은 일수",
    empty: "조건을 입력하면 예상 연차가 표시됩니다.",
    note: "통상시급 × 1일 소정근로시간 × 남은 연차의 단순 추정치입니다. 평균임금 적용, 회사 규정, 휴직·휴업, 사용촉진 절차 등에 따라 실제 지급액이 달라질 수 있습니다.",
    explanationTitle: "계산 기준",
    explanation: [
      "1년 미만 또는 출근율 80% 미만이면 1개월 개근 시 1일을 계산합니다.",
      "출근율 80% 이상인 1년 이상 근로자는 15일을 기본으로, 3년차부터 매 2년마다 1일을 더하며 최대 25일입니다.",
    ],
    cautionsTitle: "확인할 점",
    cautions: [
      "완료한 근속연수만 입력하며, 첫 1년에는 개근한 달 수를 입력하세요.",
      "법정 출근 간주 기간, 연차 사용촉진, 평균임금 적용 여부는 이 계산기에 반영되지 않습니다.",
    ],
    faq: [
      [
        "첫 1년에는 최대 며칠인가요?",
        "각 1개월 개근마다 1일씩, 최초 1년이 끝나기 전까지 최대 11일로 계산합니다.",
      ],
      [
        "연차수당은 어떻게 추정하나요?",
        "통상시급에 1일 소정근로시간과 남은 연차 일수를 곱합니다.",
      ],
    ],
  },
  en: {
    title: "Annual Leave Allowance Calculator",
    metaTitle: "Annual Leave Allowance Calculator",
    category: "Employment and leave calculator",
    description:
      "Estimate Korean statutory leave days and unused annual-leave allowance from service, attendance, and ordinary hourly wage.",
    intro:
      "A planning estimate based on the core rules in Article 60 of Korea's Labor Standards Act.",
    input: "Service and attendance",
    completedYears: "Completed service years",
    years: "years",
    attendance: "Attendance was at least 80% in the preceding year",
    fullMonths: "Full-attendance months",
    months: "months",
    usedDays: "Leave already used",
    hourlyWage: "Ordinary hourly wage",
    dailyHours: "Daily scheduled hours",
    won: "KRW",
    days: "days",
    calculate: "Calculate leave",
    reset: "Reset",
    error: "Check the highlighted values.",
    result: "Estimated allowance",
    allowance: "Unused-leave allowance",
    dailyWage: "Daily ordinary wage",
    granted: "Granted days",
    seniority: "Seniority addition",
    remaining: "Remaining days",
    empty: "Enter your conditions to estimate annual leave.",
    note: "A simple ordinary hourly wage × daily hours × remaining days estimate. Actual pay can differ if average wage applies or due to company rules, protected absences, and leave-use promotion.",
    explanationTitle: "Calculation basis",
    explanation: [
      "Before one year, or below 80% annual attendance, one day is counted for each full-attendance month.",
      "At least one completed year and 80% attendance gives 15 days; one day is added every two years from year three, capped at 25.",
    ],
    cautionsTitle: "Important cautions",
    cautions: [
      "Enter completed service years; during the first year, enter completed full-attendance months.",
      "Statutory deemed-attendance periods, leave-use promotion, and an average-wage basis are outside this estimate.",
    ],
    faq: [
      [
        "What is the first-year maximum?",
        "One day per full-attendance month, up to 11 days before the first year ends.",
      ],
      [
        "How is the allowance estimated?",
        "Ordinary hourly wage is multiplied by daily scheduled hours and remaining leave days.",
      ],
    ],
  },
} as const;
