export type SalaryRaiseLocale = "ko" | "en";
export const salaryRaiseContent = {
  ko: {
    title: "연봉 인상률 계산기",
    metaTitle: "연봉 인상률 계산기 | 인상 후 급여 계산",
    description:
      "현재 연봉 또는 월급과 인상률을 입력해 인상 후 연봉·월급과 증가액을 계산합니다.",
    category: "근로·급여 계산기",
    intro: "연봉 협상과 급여 계획에 필요한 인상 전후 금액을 한눈에 비교하세요.",
    input: "급여 인상 조건",
    annual: "연봉 기준",
    monthly: "월급 기준",
    salary: "현재 급여",
    annualPlaceholder: "예: 50,000,000",
    monthlyPlaceholder: "예: 4,000,000",
    raiseRate: "인상률",
    ratePlaceholder: "예: 5",
    calculate: "인상 급여 계산하기",
    reset: "초기화",
    error: "입력값을 확인해 주세요.",
    result: "예상 결과",
    newAnnual: "인상 후 연봉",
    annualIncrease: "연간 증가액",
    monthlyIncrease: "월 증가액",
    note: "세전 명목급여 기준이며 세금·4대보험 변화는 반영하지 않습니다.",
    details: "인상 전후 상세",
    currentAnnual: "현재 연봉",
    currentMonthly: "현재 월급",
    newMonthly: "인상 후 월급",
    appliedRate: "적용 인상률",
    empty: "계산하면 인상 전후 급여가 표시됩니다.",
    explanationTitle: "계산 방법",
    explanation: [
      "인상 후 급여는 현재 급여에 (1 + 인상률 ÷ 100)을 곱합니다.",
      "연봉 입력은 12로 나누어 월급을 계산하고, 월급 입력은 12를 곱해 연봉으로 환산합니다.",
      "증가액은 인상 후 급여에서 현재 급여를 뺀 값입니다.",
    ],
    cautionsTitle: "중요한 주의사항",
    cautions: [
      "상여금·성과급·비과세 수당이 포함되지 않은 기본적인 세전 비교입니다.",
      "실수령액 변화는 소득세, 4대보험, 공제 조건에 따라 인상률과 다를 수 있습니다.",
      "회사별 연봉 구성과 지급 횟수를 확인한 뒤 협상 자료로 활용하세요.",
    ],
    faq: [
      [
        "5% 인상은 현재 연봉에 어떻게 적용되나요?",
        "현재 연봉에 1.05를 곱하며 차액이 연간 증가액입니다.",
      ],
      [
        "월급으로도 계산할 수 있나요?",
        "네. 월급 기준을 선택하면 연봉 환산액과 월 증가액을 함께 보여드립니다.",
      ],
      [
        "상여금도 포함되나요?",
        "입력한 급여에 포함된 것으로만 계산하므로 별도 상여는 직접 합산해야 합니다.",
      ],
      [
        "실수령액도 같은 비율로 늘어나나요?",
        "아닙니다. 누진세와 보험료 기준 때문에 실제 증가율은 달라질 수 있습니다.",
      ],
    ],
  },
  en: {
    title: "Salary Raise Calculator",
    metaTitle: "Salary Raise Calculator",
    description:
      "Enter a current annual or monthly salary and raise percentage to calculate the new salary and increase amounts.",
    category: "Employment calculator",
    intro:
      "Compare pay before and after a raise for salary negotiations and planning.",
    input: "Raise inputs",
    annual: "Annual salary",
    monthly: "Monthly salary",
    salary: "Current salary",
    annualPlaceholder: "e.g. 50,000,000",
    monthlyPlaceholder: "e.g. 4,000,000",
    raiseRate: "Raise rate",
    ratePlaceholder: "e.g. 5",
    calculate: "Calculate raised salary",
    reset: "Reset",
    error: "Check the highlighted values.",
    result: "Estimated result",
    newAnnual: "New annual salary",
    annualIncrease: "Annual increase",
    monthlyIncrease: "Monthly increase",
    note: "A gross nominal-pay comparison excluding tax and social-insurance changes.",
    details: "Before and after",
    currentAnnual: "Current annual salary",
    currentMonthly: "Current monthly salary",
    newMonthly: "New monthly salary",
    appliedRate: "Applied raise rate",
    empty: "Calculate to see pay before and after the raise.",
    explanationTitle: "How it is calculated",
    explanation: [
      "New salary equals current salary multiplied by (1 + raise rate ÷ 100).",
      "Annual salary is divided by 12 for a monthly figure; monthly salary is multiplied by 12 for an annual figure.",
      "The increase is new salary minus current salary.",
    ],
    cautionsTitle: "Important cautions",
    cautions: [
      "This is a gross comparison and excludes bonuses, incentives, and separate allowances unless included in your input.",
      "Take-home pay may change by a different percentage because of progressive tax and contribution rules.",
      "Check your employer's salary composition and payment frequency before using the result in negotiations.",
    ],
    faq: [
      [
        "How is a 5% raise applied?",
        "The current salary is multiplied by 1.05; the difference is the increase.",
      ],
      [
        "Can I start with monthly pay?",
        "Yes. Select monthly salary to see both annualized pay and the monthly increase.",
      ],
      [
        "Are bonuses included?",
        "Only if they are already included in the salary value you enter.",
      ],
      [
        "Will take-home pay rise by the same rate?",
        "Not necessarily. Tax and social-insurance thresholds can change the net percentage.",
      ],
    ],
  },
} as const;
