export type PublishedCalculator = {
  id: string;
  name: string;
  description: string;
  keywords: readonly string[];
  category: "금융";
  href: `/ko/${"finance" | "employment"}/${string}`;
};

export const publishedCalculators = [
  {
    id: "ltv",
    name: "LTV 계산기",
    description: "담보가치와 대출금액으로 예상 LTV와 대출 여력을 계산합니다.",
    keywords: ["LTV", "담보인정비율", "주택담보대출", "loan to value"],
    category: "금융",
    href: "/ko/finance/ltv",
  },
  {
    id: "dsr",
    name: "DSR 계산기",
    description: "연소득과 대출 원리금 상환액으로 예상 DSR을 계산합니다.",
    keywords: [
      "DSR",
      "총부채원리금상환비율",
      "대출 한도",
      "debt service ratio",
    ],
    category: "금융",
    href: "/ko/finance/dsr",
  },
  {
    id: "weekly-holiday-pay",
    name: "주휴수당 계산기",
    description: "시급과 주 소정근로시간으로 예상 주휴수당을 계산합니다.",
    keywords: ["주휴수당", "시급", "주급", "근로시간", "weekly holiday pay"],
    category: "금융",
    href: "/ko/employment/weekly-holiday-pay",
  },
  {
    id: "cagr",
    name: "CAGR 계산기",
    description: "시작값과 종료값의 연평균 복합성장률과 총수익률을 계산합니다.",
    keywords: ["cagr", "연평균", "성장률", "수익률", "투자"],
    category: "금융",
    href: "/ko/finance/cagr",
  },
  {
    id: "deposit",
    name: "예금 계산기",
    description: "목돈 예금의 세전·세후 이자와 예상 만기액을 계산합니다.",
    keywords: ["예금", "deposit", "목돈", "만기", "이자"],
    category: "금융",
    href: "/ko/finance/fixed-deposit",
  },
  {
    id: "savings",
    name: "적금 계산기",
    description: "정기 납입 적금의 세전·세후 이자와 예상 만기액을 계산합니다.",
    keywords: ["적금", "savings", "저축", "납입", "이자"],
    category: "금융",
    href: "/ko/finance/savings",
  },
  {
    id: "loan",
    name: "대출 계산기",
    description: "상환 방식별 월 납부액, 총 이자와 상환 일정을 계산합니다.",
    keywords: ["대출", "loan", "상환", "원리금", "이자"],
    category: "금융",
    href: "/ko/finance/loan",
  },
  {
    id: "compound-interest",
    name: "복리 계산기",
    description: "초기 투자금과 정기 납입액의 예상 복리 성장을 계산합니다.",
    keywords: ["복리", "compound interest", "투자", "저축", "이자"],
    category: "금융",
    href: "/ko/finance/compound-interest",
  },
  {
    id: "severance-pay",
    name: "퇴직금 계산기",
    description: "평균임금과 계속근로기간으로 예상 법정 퇴직금을 계산합니다.",
    keywords: ["퇴직금", "severance", "평균임금", "근속기간"],
    category: "금융",
    href: "/ko/employment/severance-pay",
  },
  {
    id: "unemployment-benefits",
    name: "실업급여 계산기",
    description: "평균임금과 고용보험 가입기간으로 예상 구직급여를 계산합니다.",
    keywords: ["실업급여", "구직급여", "고용보험", "unemployment"],
    category: "금융",
    href: "/ko/employment/unemployment-benefits",
  },
  {
    id: "net-salary",
    name: "실수령액 계산기",
    description:
      "급여에서 4대보험과 예상 세금을 뺀 월·연 실수령액을 계산합니다.",
    keywords: ["연봉", "월급", "실수령액", "4대보험", "take home pay"],
    category: "금융",
    href: "/ko/employment/net-salary",
  },
  {
    id: "hourly-wage",
    name: "시급 계산기",
    description: "시급·일급·주급·월급·연봉을 같은 시간급 기준으로 환산합니다.",
    keywords: ["시급", "월급", "연봉", "임금 환산", "hourly wage"],
    category: "금융",
    href: "/ko/employment/hourly-wage",
  },
  {
    id: "social-insurance",
    name: "4대보험 계산기",
    description:
      "월 보수로 근로자와 사업주의 예상 4대보험 부담액을 계산합니다.",
    keywords: [
      "4대보험",
      "국민연금",
      "건강보험",
      "고용보험",
      "social insurance",
    ],
    category: "금융",
    href: "/ko/employment/social-insurance",
  },
  {
    id: "average-wage",
    name: "평균임금 계산기",
    description: "임금총액과 산정기간 총일수로 1일 평균임금을 계산합니다.",
    keywords: ["평균임금", "임금총액", "퇴직금", "average wage"],
    category: "금융",
    href: "/ko/employment/average-wage",
  },
  {
    id: "salary-raise",
    name: "연봉 인상률 계산기",
    description:
      "현재 급여와 인상률로 인상 후 연봉·월급과 증가액을 계산합니다.",
    keywords: ["연봉 인상률", "급여 인상", "연봉 협상", "salary raise"],
    category: "금융",
    href: "/ko/employment/salary-raise",
  },
  {
    id: "salary-conversion",
    name: "연봉·월급 환산 계산기",
    description: "연봉과 월급을 같은 급여 기준으로 간편하게 환산합니다.",
    keywords: ["연봉 환산", "월급 환산", "급여 환산", "salary conversion"],
    category: "금융",
    href: "/ko/employment/salary-conversion",
  },
  {
    id: "overtime-pay",
    name: "연장근로수당 계산기",
    description: "통상시급과 연장근로시간으로 예상 시간외수당을 계산합니다.",
    keywords: ["연장근로수당", "시간외수당", "가산임금", "overtime pay"],
    category: "금융",
    href: "/ko/employment/overtime-pay",
  },
  {
    id: "night-work-pay",
    name: "야간근로수당 계산기",
    description: "통상시급과 야간근로시간으로 예상 야간수당을 계산합니다.",
    keywords: ["야간근로수당", "야간수당", "가산임금", "night work pay"],
    category: "금융",
    href: "/ko/employment/night-work-pay",
  },
  {
    id: "holiday-work-pay",
    name: "휴일근로수당 계산기",
    description: "통상시급과 휴일근로시간으로 예상 휴일수당을 계산합니다.",
    keywords: ["휴일근로수당", "휴일수당", "holiday work pay"],
    category: "금융",
    href: "/ko/employment/holiday-work-pay",
  },
  {
    id: "minimum-wage",
    name: "최저임금 계산기",
    description: "주 소정근로시간별 2026년 최저 주급과 월 환산액을 계산합니다.",
    keywords: ["최저임금", "최저시급", "최저 주급", "minimum wage"],
    category: "금융",
    href: "/ko/employment/minimum-wage",
  },
  {
    id: "annual-leave-allowance",
    name: "연차수당 계산기",
    description:
      "근속·출근 조건과 통상시급으로 예상 미사용 연차수당을 계산합니다.",
    keywords: ["연차", "유급휴가", "연차 일수", "annual leave"],
    category: "금융",
    href: "/ko/employment/annual-leave-allowance",
  },
  {
    id: "retirement-pension",
    name: "퇴직연금 계산기",
    description: "월 적립액과 예상 수익률로 퇴직연금의 미래 가치를 계산합니다.",
    keywords: ["퇴직연금", "연금", "노후", "retirement pension"],
    category: "금융",
    href: "/ko/employment/retirement-pension",
  },
  {
    id: "gross-up-salary",
    name: "세전 급여 역산 계산기",
    description: "목표 실수령액과 공제율로 필요한 세전 연봉·월급을 역산합니다.",
    keywords: ["세전 급여", "급여 역산", "실수령액", "gross up salary"],
    category: "금융",
    href: "/ko/employment/gross-up-salary",
  },
  {
    id: "loan-interest-comparison",
    name: "대출 이자 비교 계산기",
    description:
      "같은 원금과 기간에서 두 금리의 월 상환액과 총이자를 비교합니다.",
    keywords: [
      "대출 이자 비교",
      "대출 금리 비교",
      "이자 절감",
      "loan comparison",
    ],
    category: "금융",
    href: "/ko/finance/loan-interest-comparison",
  },
  {
    id: "loan-refinancing-savings",
    name: "대출 대환 절감 계산기",
    description: "대환 전후의 이자와 비용을 비교해 순절감액을 계산합니다.",
    keywords: ["대환대출", "대출 갈아타기", "이자 절감", "refinancing"],
    category: "금융",
    href: "/ko/finance/loan-refinancing-savings",
  },
  {
    id: "balloon-payment",
    name: "만기 일시상환액 계산기",
    description: "월 납입액과 만기에 남는 큰 상환액, 총이자를 계산합니다.",
    keywords: [
      "만기 일시상환",
      "벌룬 페이먼트",
      "대출 상환",
      "balloon payment",
    ],
    category: "금융",
    href: "/ko/finance/balloon-payment",
  },
  {
    id: "mortgage-payment",
    name: "주택담보대출 상환액 계산기",
    description:
      "주택가격과 자기자금으로 월 원리금과 예상 주거비를 계산합니다.",
    keywords: ["주택담보대출", "모기지", "월 상환액", "mortgage payment"],
    category: "금융",
    href: "/ko/finance/mortgage-payment",
  },
  {
    id: "jeonse-loan-interest",
    name: "전세대출 이자 계산기",
    description: "전세보증금과 자기자금으로 월 이자와 총이자를 계산합니다.",
    keywords: ["전세대출", "전세자금대출", "전세 이자", "jeonse loan"],
    category: "금융",
    href: "/ko/finance/jeonse-loan-interest",
  },
  {
    id: "credit-loan-interest",
    name: "신용대출 이자 계산기",
    description: "대출금과 금리로 월 이자와 기간 전체 비용을 계산합니다.",
    keywords: ["신용대출", "신용대출 이자", "개인신용대출", "credit loan"],
    category: "금융",
    href: "/ko/finance/credit-loan-interest",
  },
  {
    id: "early-loan-repayment-fee",
    name: "대출 중도상환수수료 계산기",
    description:
      "상환금액과 남은 약정기간으로 예상 중도상환수수료를 계산합니다.",
    keywords: [
      "중도상환수수료",
      "대출 조기상환",
      "상환 수수료",
      "prepayment fee",
    ],
    category: "금융",
    href: "/ko/finance/early-loan-repayment-fee",
  },
  {
    id: "dti",
    name: "DTI 계산기",
    description: "연소득과 부채 상환액으로 예상 DTI를 계산합니다.",
    keywords: ["DTI", "총부채상환비율", "주택담보대출", "debt to income"],
    category: "금융",
    href: "/ko/finance/dti",
  },
  {
    id: "real-estate-acquisition-tax",
    name: "부동산 취득세 계산기",
    description: "취득가액과 적용 세율로 예상 취득세와 총 비용을 계산합니다.",
    keywords: ["부동산 취득세", "취득세", "지방교육세", "acquisition tax"],
    category: "금융",
    href: "/ko/finance/real-estate-acquisition-tax",
  },
  {
    id: "capital-gains-tax",
    name: "양도소득세 계산기",
    description:
      "양도가액과 취득가액, 비용과 확인한 세율로 예상 세금을 계산합니다.",
    keywords: ["양도소득세", "양도차익", "자본이득세", "capital gains tax"],
    category: "금융",
    href: "/ko/finance/capital-gains-tax",
  },
  {
    id: "gift-tax",
    name: "증여세 계산기",
    description:
      "증여 재산가액과 확인한 공제액·세율로 예상 증여세를 계산합니다.",
    keywords: ["증여세", "증여재산공제", "과세표준", "gift tax"],
    category: "금융",
    href: "/ko/finance/gift-tax",
  },
  {
    id: "inheritance-tax",
    name: "상속세 계산기",
    description:
      "총상속재산과 확인한 채무·비용·공제액·세율로 예상 상속세를 계산합니다.",
    keywords: ["상속세", "상속공제", "과세표준", "inheritance tax"],
    category: "금융",
    href: "/ko/finance/inheritance-tax",
  },
  {
    id: "property-tax",
    name: "재산세 계산기",
    description:
      "시가표준액과 확인한 과세표준 비율·세율로 예상 재산세를 계산합니다.",
    keywords: ["재산세", "과세표준", "지방교육세", "property tax"],
    category: "금융",
    href: "/ko/finance/property-tax",
  },
  {
    id: "comprehensive-real-estate-holding-tax",
    name: "종합부동산세 계산기",
    description:
      "합산 공시가격과 확인한 공제액·비율·세율로 예상 종합부동산세를 계산합니다.",
    keywords: [
      "종합부동산세",
      "종부세",
      "공시가격",
      "comprehensive real estate holding tax",
    ],
    category: "금융",
    href: "/ko/finance/comprehensive-real-estate-holding-tax",
  },
  {
    id: "value-added-tax",
    name: "부가가치세 계산기",
    description:
      "공급가액에 부가세를 더하거나 합계금액에서 공급가액과 부가세를 역산합니다.",
    keywords: ["부가가치세", "부가세", "공급가액", "VAT"],
    category: "금융",
    href: "/ko/finance/value-added-tax",
  },
  {
    id: "comprehensive-income-tax",
    name: "종합소득세 계산기",
    description:
      "총수입금액과 필요경비, 확인한 공제액·세율로 예상 종합소득세를 계산합니다.",
    keywords: ["종합소득세", "종합소득", "과세표준", "income tax"],
    category: "금융",
    href: "/ko/finance/comprehensive-income-tax",
  },
  {
    id: "withholding-tax",
    name: "원천징수세 계산기",
    description:
      "지급액과 확인한 비과세 금액·세율로 예상 원천징수세와 실수령액을 계산합니다.",
    keywords: ["원천징수", "원천징수세", "소득세", "withholding tax"],
    category: "금융",
    href: "/ko/finance/withholding-tax",
  },
] as const satisfies readonly PublishedCalculator[];
